services:
  web:
    image: tecnica_web
    container_name: contenedor_tecnica
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flutter
    networks:
      - app_net

  flutter:
    build: .
    container_name: flutter_web
    restart: always
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
